### ISSUE TITLE
Issue with business id's with special characters and /businesses/{id} endpoint

### ISSUE THREAD

**Issue by idjuradj** [danieljin/yelpv3#4]
When passing business ids that contain specials chars to business and reviews methods - it causes the call to /businesses/{id} to malfunction.
Example of problematic ids:
`maison-d-être-london-6`
`regency-café-london-2`

Can you investigate that? 
Most probably additional encoding from request is causing the issue.

**Comment by lhxatus** [comment]
you will need to encode  business id before pass it to the search function.
I had the same problem and encode business id works for me.

**Comment by idjuradj** [comment]
@lhxatus That solved the issue. Thanks.
